# code taken from chatGPT

name: Lint and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/job_ads.db'
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.LLM_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pytest dotenv google-genai
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install PySimpleGUI
        run: |
          python -m pip install -i https://PySimpleGUI.net/install PySimpleGUI

      - name: Run flake8 (Linter)
        run: flake8 . --max-line-length=127

      - name: Run black (Code Formatter Check)
        run: black --check --verbose --diff --color --skip-string-normalization --skip-magic-trailing-comma .

      - name: Run pytest (Tests)
        run: pytest 'tests.py'
